global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.5.0.4:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['10.5.0.2:8081']